idf_component_register(SRCS "main.cpp"
                            "quimblos/engine.cpp"
                            "util/color.cpp"
                            "driver/system/blufi.cpp"
                            "driver/system/blufi_security.cpp"
                            "driver/system/wifi.cpp"
                            "driver/websocket_keep_alive.cpp"
                            "driver/websocket.cpp"
                            "driver/ws281x.cpp"
                            "voxel/driver.cpp"
                            "voxel/impulse.cpp"
                       INCLUDE_DIRS "."
                       PRIV_REQUIRES esp_driver_rmt bt nvs_flash mbedtls esp_https_server esp_timer
                       EMBED_TXTFILES "certs/servercert.pem"
                                   "certs/prvtkey.pem")
